# Generated by Django 6.1.1 on 2026-09-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='role',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
