# Generated by Django 6.1.1 on 2026-09-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_employee_inactivated_at_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='inactivated_at',
        ),
        migrations.AddField(
            model_name='employee',
            name='inactivated_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
